[package]
name = "mpv-ytdl-gui-rs"
version = "0.1.0"
license = "GPL-3"
edition = "2021"

[dependencies]
cxx = "1.0"
pyo3 = "0.21"

[dev-dependencies]
cxxbridge-cmd = "1.0"

[lib]
crate-type=["staticlib"]
